export default function Head() {
  return (
    <>
      <title>In Gia Linh</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="public/images/logo/logo-2.svg" />
    </>
  );
}
